// dart format width=80
import 'package:drift/internal/versioned_schema.dart' as i0;
import 'package:drift/drift.dart' as i1;
import 'package:drift/drift.dart'; // GENERATED BY drift_dev, DO NOT MODIFY.

// ignore_for_file: type=lint,unused_import
//
final class Schema2 extends i0.VersionedSchema {
  Schema2({required super.database}) : super(version: 2);
  @override
  late final List<i1.DatabaseSchemaEntity> entities = [
    debts,
    appMeta,
    scenarios,
  ];
  late final Shape0 debts = Shape0(
    source: i0.VersionedTable(
      entityName: 'debts',
      withoutRowId: false,
      isStrict: false,
      tableConstraints: ['PRIMARY KEY(id)'],
      columns: [
        _column_0,
        _column_1,
        _column_2,
        _column_3,
        _column_4,
        _column_5,
        _column_6,
        _column_7,
        _column_8,
        _column_9,
        _column_10,
        _column_11,
        _column_12,
      ],
      attachedDatabase: database,
    ),
    alias: null,
  );
  late final Shape1 appMeta = Shape1(
    source: i0.VersionedTable(
      entityName: 'app_meta',
      withoutRowId: false,
      isStrict: false,
      tableConstraints: ['PRIMARY KEY("key")'],
      columns: [_column_13, _column_14],
      attachedDatabase: database,
    ),
    alias: null,
  );
  late final Shape2 scenarios = Shape2(
    source: i0.VersionedTable(
      entityName: 'scenarios',
      withoutRowId: false,
      isStrict: false,
      tableConstraints: ['PRIMARY KEY(id)'],
      columns: [
        _column_0,
        _column_1,
        _column_15,
        _column_16,
        _column_17,
        _column_18,
        _column_19,
        _column_20,
        _column_21,
        _column_22,
        _column_11,
      ],
      attachedDatabase: database,
    ),
    alias: null,
  );
}

class Shape0 extends i0.VersionedTable {
  Shape0({required super.source, required super.alias}) : super.aliased();
  i1.GeneratedColumn<String> get id =>
      columnsByName['id']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get name =>
      columnsByName['name']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get type =>
      columnsByName['type']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<int> get balanceMinor =>
      columnsByName['balance_minor']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<int> get aprBps =>
      columnsByName['apr_bps']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<int> get minPaymentPercentBps =>
      columnsByName['min_payment_percent_bps']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<int> get minPaymentFloorMinor =>
      columnsByName['min_payment_floor_minor']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<int> get allowsOverpayment =>
      columnsByName['allows_overpayment']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<int> get promoAprBps =>
      columnsByName['promo_apr_bps']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<int> get promoEndsYearMonth =>
      columnsByName['promo_ends_year_month']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<int> get sortIndex =>
      columnsByName['sort_index']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<int> get createdAt =>
      columnsByName['created_at']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<int> get updatedAt =>
      columnsByName['updated_at']! as i1.GeneratedColumn<int>;
}

i1.GeneratedColumn<String> _column_0(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'id',
      aliasedName,
      false,
      type: i1.DriftSqlType.string,
      $customConstraints: 'NOT NULL',
    );
i1.GeneratedColumn<String> _column_1(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'name',
      aliasedName,
      false,
      type: i1.DriftSqlType.string,
      $customConstraints: 'NOT NULL',
    );
i1.GeneratedColumn<String> _column_2(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'type',
      aliasedName,
      false,
      type: i1.DriftSqlType.string,
      $customConstraints: 'NOT NULL',
    );
i1.GeneratedColumn<int> _column_3(String aliasedName) =>
    i1.GeneratedColumn<int>(
      'balance_minor',
      aliasedName,
      false,
      type: i1.DriftSqlType.int,
      $customConstraints: 'NOT NULL',
    );
i1.GeneratedColumn<int> _column_4(String aliasedName) =>
    i1.GeneratedColumn<int>(
      'apr_bps',
      aliasedName,
      false,
      type: i1.DriftSqlType.int,
      $customConstraints: 'NOT NULL',
    );
i1.GeneratedColumn<int> _column_5(String aliasedName) =>
    i1.GeneratedColumn<int>(
      'min_payment_percent_bps',
      aliasedName,
      false,
      type: i1.DriftSqlType.int,
      $customConstraints: 'NOT NULL',
    );
i1.GeneratedColumn<int> _column_6(String aliasedName) =>
    i1.GeneratedColumn<int>(
      'min_payment_floor_minor',
      aliasedName,
      false,
      type: i1.DriftSqlType.int,
      $customConstraints: 'NOT NULL',
    );
i1.GeneratedColumn<int> _column_7(String aliasedName) =>
    i1.GeneratedColumn<int>(
      'allows_overpayment',
      aliasedName,
      false,
      type: i1.DriftSqlType.int,
      $customConstraints: 'NOT NULL CHECK (allows_overpayment IN (0, 1))',
    );
i1.GeneratedColumn<int> _column_8(String aliasedName) =>
    i1.GeneratedColumn<int>(
      'promo_apr_bps',
      aliasedName,
      true,
      type: i1.DriftSqlType.int,
      $customConstraints: 'NULL',
    );
i1.GeneratedColumn<int> _column_9(String aliasedName) =>
    i1.GeneratedColumn<int>(
      'promo_ends_year_month',
      aliasedName,
      true,
      type: i1.DriftSqlType.int,
      $customConstraints: 'NULL',
    );
i1.GeneratedColumn<int> _column_10(String aliasedName) =>
    i1.GeneratedColumn<int>(
      'sort_index',
      aliasedName,
      false,
      type: i1.DriftSqlType.int,
      $customConstraints: 'NOT NULL',
    );
i1.GeneratedColumn<int> _column_11(String aliasedName) =>
    i1.GeneratedColumn<int>(
      'created_at',
      aliasedName,
      false,
      type: i1.DriftSqlType.int,
      $customConstraints: 'NOT NULL',
    );
i1.GeneratedColumn<int> _column_12(String aliasedName) =>
    i1.GeneratedColumn<int>(
      'updated_at',
      aliasedName,
      false,
      type: i1.DriftSqlType.int,
      $customConstraints: 'NOT NULL',
    );

class Shape1 extends i0.VersionedTable {
  Shape1({required super.source, required super.alias}) : super.aliased();
  i1.GeneratedColumn<String> get key =>
      columnsByName['key']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get value =>
      columnsByName['value']! as i1.GeneratedColumn<String>;
}

i1.GeneratedColumn<String> _column_13(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'key',
      aliasedName,
      false,
      type: i1.DriftSqlType.string,
      $customConstraints: 'NOT NULL',
    );
i1.GeneratedColumn<String> _column_14(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'value',
      aliasedName,
      false,
      type: i1.DriftSqlType.string,
      $customConstraints: 'NOT NULL',
    );

class Shape2 extends i0.VersionedTable {
  Shape2({required super.source, required super.alias}) : super.aliased();
  i1.GeneratedColumn<String> get id =>
      columnsByName['id']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get name =>
      columnsByName['name']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<int> get monthlyBudgetMinor =>
      columnsByName['monthly_budget_minor']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<int> get consolidationAprBps =>
      columnsByName['consolidation_apr_bps']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<int> get consolidationTermMonths =>
      columnsByName['consolidation_term_months']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<int> get consolidationFeeBps =>
      columnsByName['consolidation_fee_bps']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<int> get transferFeeBps =>
      columnsByName['transfer_fee_bps']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<int> get promoMonths =>
      columnsByName['promo_months']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<int> get revertAprBps =>
      columnsByName['revert_apr_bps']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<int> get transferCreditLimitMinor =>
      columnsByName['transfer_credit_limit_minor']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<int> get createdAt =>
      columnsByName['created_at']! as i1.GeneratedColumn<int>;
}

i1.GeneratedColumn<int> _column_15(String aliasedName) =>
    i1.GeneratedColumn<int>(
      'monthly_budget_minor',
      aliasedName,
      false,
      type: i1.DriftSqlType.int,
      $customConstraints: 'NOT NULL',
    );
i1.GeneratedColumn<int> _column_16(String aliasedName) =>
    i1.GeneratedColumn<int>(
      'consolidation_apr_bps',
      aliasedName,
      false,
      type: i1.DriftSqlType.int,
      $customConstraints: 'NOT NULL',
    );
i1.GeneratedColumn<int> _column_17(String aliasedName) =>
    i1.GeneratedColumn<int>(
      'consolidation_term_months',
      aliasedName,
      false,
      type: i1.DriftSqlType.int,
      $customConstraints: 'NOT NULL',
    );
i1.GeneratedColumn<int> _column_18(String aliasedName) =>
    i1.GeneratedColumn<int>(
      'consolidation_fee_bps',
      aliasedName,
      false,
      type: i1.DriftSqlType.int,
      $customConstraints: 'NOT NULL',
    );
i1.GeneratedColumn<int> _column_19(String aliasedName) =>
    i1.GeneratedColumn<int>(
      'transfer_fee_bps',
      aliasedName,
      false,
      type: i1.DriftSqlType.int,
      $customConstraints: 'NOT NULL',
    );
i1.GeneratedColumn<int> _column_20(String aliasedName) =>
    i1.GeneratedColumn<int>(
      'promo_months',
      aliasedName,
      false,
      type: i1.DriftSqlType.int,
      $customConstraints: 'NOT NULL',
    );
i1.GeneratedColumn<int> _column_21(String aliasedName) =>
    i1.GeneratedColumn<int>(
      'revert_apr_bps',
      aliasedName,
      false,
      type: i1.DriftSqlType.int,
      $customConstraints: 'NOT NULL',
    );
i1.GeneratedColumn<int> _column_22(String aliasedName) =>
    i1.GeneratedColumn<int>(
      'transfer_credit_limit_minor',
      aliasedName,
      true,
      type: i1.DriftSqlType.int,
      $customConstraints: 'NULL',
    );

final class Schema3 extends i0.VersionedSchema {
  Schema3({required super.database}) : super(version: 3);
  @override
  late final List<i1.DatabaseSchemaEntity> entities = [
    debts,
    appMeta,
    scenarios,
  ];
  late final Shape3 debts = Shape3(
    source: i0.VersionedTable(
      entityName: 'debts',
      withoutRowId: false,
      isStrict: false,
      tableConstraints: ['PRIMARY KEY(id)'],
      columns: [
        _column_0,
        _column_1,
        _column_2,
        _column_3,
        _column_4,
        _column_5,
        _column_6,
        _column_7,
        _column_8,
        _column_9,
        _column_23,
        _column_24,
        _column_25,
        _column_26,
        _column_10,
        _column_11,
        _column_12,
      ],
      attachedDatabase: database,
    ),
    alias: null,
  );
  late final Shape1 appMeta = Shape1(
    source: i0.VersionedTable(
      entityName: 'app_meta',
      withoutRowId: false,
      isStrict: false,
      tableConstraints: ['PRIMARY KEY("key")'],
      columns: [_column_13, _column_14],
      attachedDatabase: database,
    ),
    alias: null,
  );
  late final Shape2 scenarios = Shape2(
    source: i0.VersionedTable(
      entityName: 'scenarios',
      withoutRowId: false,
      isStrict: false,
      tableConstraints: ['PRIMARY KEY(id)'],
      columns: [
        _column_0,
        _column_1,
        _column_15,
        _column_16,
        _column_17,
        _column_18,
        _column_19,
        _column_20,
        _column_21,
        _column_22,
        _column_11,
      ],
      attachedDatabase: database,
    ),
    alias: null,
  );
}

class Shape3 extends i0.VersionedTable {
  Shape3({required super.source, required super.alias}) : super.aliased();
  i1.GeneratedColumn<String> get id =>
      columnsByName['id']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get name =>
      columnsByName['name']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get type =>
      columnsByName['type']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<int> get balanceMinor =>
      columnsByName['balance_minor']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<int> get aprBps =>
      columnsByName['apr_bps']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<int> get minPaymentPercentBps =>
      columnsByName['min_payment_percent_bps']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<int> get minPaymentFloorMinor =>
      columnsByName['min_payment_floor_minor']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<int> get allowsOverpayment =>
      columnsByName['allows_overpayment']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<int> get promoAprBps =>
      columnsByName['promo_apr_bps']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<int> get promoEndsYearMonth =>
      columnsByName['promo_ends_year_month']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<int> get offerFeeBps =>
      columnsByName['offer_fee_bps']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<int> get offerPromoAprBps =>
      columnsByName['offer_promo_apr_bps']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<int> get offerPromoMonths =>
      columnsByName['offer_promo_months']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<int> get offerAvailableCreditMinor =>
      columnsByName['offer_available_credit_minor']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<int> get sortIndex =>
      columnsByName['sort_index']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<int> get createdAt =>
      columnsByName['created_at']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<int> get updatedAt =>
      columnsByName['updated_at']! as i1.GeneratedColumn<int>;
}

i1.GeneratedColumn<int> _column_23(String aliasedName) =>
    i1.GeneratedColumn<int>(
      'offer_fee_bps',
      aliasedName,
      true,
      type: i1.DriftSqlType.int,
      $customConstraints: 'NULL',
    );
i1.GeneratedColumn<int> _column_24(String aliasedName) =>
    i1.GeneratedColumn<int>(
      'offer_promo_apr_bps',
      aliasedName,
      true,
      type: i1.DriftSqlType.int,
      $customConstraints: 'NULL',
    );
i1.GeneratedColumn<int> _column_25(String aliasedName) =>
    i1.GeneratedColumn<int>(
      'offer_promo_months',
      aliasedName,
      true,
      type: i1.DriftSqlType.int,
      $customConstraints: 'NULL',
    );
i1.GeneratedColumn<int> _column_26(String aliasedName) =>
    i1.GeneratedColumn<int>(
      'offer_available_credit_minor',
      aliasedName,
      true,
      type: i1.DriftSqlType.int,
      $customConstraints: 'NULL',
    );

final class Schema4 extends i0.VersionedSchema {
  Schema4({required super.database}) : super(version: 4);
  @override
  late final List<i1.DatabaseSchemaEntity> entities = [
    debts,
    appMeta,
    scenarios,
    checkIns,
    checkInBalances,
    startingPoints,
  ];
  late final Shape4 debts = Shape4(
    source: i0.VersionedTable(
      entityName: 'debts',
      withoutRowId: false,
      isStrict: false,
      tableConstraints: ['PRIMARY KEY(id)'],
      columns: [
        _column_0,
        _column_1,
        _column_2,
        _column_3,
        _column_4,
        _column_5,
        _column_6,
        _column_7,
        _column_8,
        _column_9,
        _column_23,
        _column_24,
        _column_25,
        _column_26,
        _column_10,
        _column_11,
        _column_12,
        _column_27,
      ],
      attachedDatabase: database,
    ),
    alias: null,
  );
  late final Shape1 appMeta = Shape1(
    source: i0.VersionedTable(
      entityName: 'app_meta',
      withoutRowId: false,
      isStrict: false,
      tableConstraints: ['PRIMARY KEY("key")'],
      columns: [_column_13, _column_14],
      attachedDatabase: database,
    ),
    alias: null,
  );
  late final Shape2 scenarios = Shape2(
    source: i0.VersionedTable(
      entityName: 'scenarios',
      withoutRowId: false,
      isStrict: false,
      tableConstraints: ['PRIMARY KEY(id)'],
      columns: [
        _column_0,
        _column_1,
        _column_15,
        _column_16,
        _column_17,
        _column_18,
        _column_19,
        _column_20,
        _column_21,
        _column_22,
        _column_11,
      ],
      attachedDatabase: database,
    ),
    alias: null,
  );
  late final Shape5 checkIns = Shape5(
    source: i0.VersionedTable(
      entityName: 'check_ins',
      withoutRowId: false,
      isStrict: false,
      tableConstraints: ['PRIMARY KEY(id)'],
      columns: [_column_0, _column_28, _column_29, _column_30],
      attachedDatabase: database,
    ),
    alias: null,
  );
  late final Shape6 checkInBalances = Shape6(
    source: i0.VersionedTable(
      entityName: 'check_in_balances',
      withoutRowId: false,
      isStrict: false,
      tableConstraints: ['PRIMARY KEY(check_in_id, debt_id)'],
      columns: [_column_31, _column_32, _column_33, _column_3],
      attachedDatabase: database,
    ),
    alias: null,
  );
  late final Shape7 startingPoints = Shape7(
    source: i0.VersionedTable(
      entityName: 'starting_points',
      withoutRowId: false,
      isStrict: false,
      tableConstraints: ['PRIMARY KEY(id)'],
      columns: [
        _column_0,
        _column_31,
        _column_28,
        _column_34,
        _column_35,
        _column_36,
        _column_37,
      ],
      attachedDatabase: database,
    ),
    alias: null,
  );
}

class Shape4 extends i0.VersionedTable {
  Shape4({required super.source, required super.alias}) : super.aliased();
  i1.GeneratedColumn<String> get id =>
      columnsByName['id']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get name =>
      columnsByName['name']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get type =>
      columnsByName['type']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<int> get balanceMinor =>
      columnsByName['balance_minor']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<int> get aprBps =>
      columnsByName['apr_bps']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<int> get minPaymentPercentBps =>
      columnsByName['min_payment_percent_bps']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<int> get minPaymentFloorMinor =>
      columnsByName['min_payment_floor_minor']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<int> get allowsOverpayment =>
      columnsByName['allows_overpayment']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<int> get promoAprBps =>
      columnsByName['promo_apr_bps']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<int> get promoEndsYearMonth =>
      columnsByName['promo_ends_year_month']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<int> get offerFeeBps =>
      columnsByName['offer_fee_bps']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<int> get offerPromoAprBps =>
      columnsByName['offer_promo_apr_bps']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<int> get offerPromoMonths =>
      columnsByName['offer_promo_months']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<int> get offerAvailableCreditMinor =>
      columnsByName['offer_available_credit_minor']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<int> get sortIndex =>
      columnsByName['sort_index']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<int> get createdAt =>
      columnsByName['created_at']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<int> get updatedAt =>
      columnsByName['updated_at']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<int> get clearedAt =>
      columnsByName['cleared_at']! as i1.GeneratedColumn<int>;
}

i1.GeneratedColumn<int> _column_27(String aliasedName) =>
    i1.GeneratedColumn<int>(
      'cleared_at',
      aliasedName,
      true,
      type: i1.DriftSqlType.int,
      $customConstraints: 'NULL',
    );

class Shape5 extends i0.VersionedTable {
  Shape5({required super.source, required super.alias}) : super.aliased();
  i1.GeneratedColumn<String> get id =>
      columnsByName['id']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<int> get at =>
      columnsByName['at']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<int> get isStart =>
      columnsByName['is_start']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<int> get totalMinor =>
      columnsByName['total_minor']! as i1.GeneratedColumn<int>;
}

i1.GeneratedColumn<int> _column_28(String aliasedName) =>
    i1.GeneratedColumn<int>(
      'at',
      aliasedName,
      false,
      type: i1.DriftSqlType.int,
      $customConstraints: 'NOT NULL',
    );
i1.GeneratedColumn<int> _column_29(String aliasedName) =>
    i1.GeneratedColumn<int>(
      'is_start',
      aliasedName,
      false,
      type: i1.DriftSqlType.int,
      $customConstraints: 'NOT NULL CHECK (is_start IN (0, 1))',
    );
i1.GeneratedColumn<int> _column_30(String aliasedName) =>
    i1.GeneratedColumn<int>(
      'total_minor',
      aliasedName,
      false,
      type: i1.DriftSqlType.int,
      $customConstraints: 'NOT NULL',
    );

class Shape6 extends i0.VersionedTable {
  Shape6({required super.source, required super.alias}) : super.aliased();
  i1.GeneratedColumn<String> get checkInId =>
      columnsByName['check_in_id']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get debtId =>
      columnsByName['debt_id']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get debtName =>
      columnsByName['debt_name']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<int> get balanceMinor =>
      columnsByName['balance_minor']! as i1.GeneratedColumn<int>;
}

i1.GeneratedColumn<String> _column_31(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'check_in_id',
      aliasedName,
      false,
      type: i1.DriftSqlType.string,
      $customConstraints: 'NOT NULL',
    );
i1.GeneratedColumn<String> _column_32(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'debt_id',
      aliasedName,
      false,
      type: i1.DriftSqlType.string,
      $customConstraints: 'NOT NULL',
    );
i1.GeneratedColumn<String> _column_33(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'debt_name',
      aliasedName,
      false,
      type: i1.DriftSqlType.string,
      $customConstraints: 'NOT NULL',
    );

class Shape7 extends i0.VersionedTable {
  Shape7({required super.source, required super.alias}) : super.aliased();
  i1.GeneratedColumn<String> get id =>
      columnsByName['id']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get checkInId =>
      columnsByName['check_in_id']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<int> get at =>
      columnsByName['at']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<String> get strategy =>
      columnsByName['strategy']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get reason =>
      columnsByName['reason']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get debtName =>
      columnsByName['debt_name']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get projectedTotalsJson =>
      columnsByName['projected_totals_json']! as i1.GeneratedColumn<String>;
}

i1.GeneratedColumn<String> _column_34(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'strategy',
      aliasedName,
      false,
      type: i1.DriftSqlType.string,
      $customConstraints: 'NOT NULL',
    );
i1.GeneratedColumn<String> _column_35(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'reason',
      aliasedName,
      false,
      type: i1.DriftSqlType.string,
      $customConstraints: 'NOT NULL',
    );
i1.GeneratedColumn<String> _column_36(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'debt_name',
      aliasedName,
      true,
      type: i1.DriftSqlType.string,
      $customConstraints: 'NULL',
    );
i1.GeneratedColumn<String> _column_37(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'projected_totals_json',
      aliasedName,
      false,
      type: i1.DriftSqlType.string,
      $customConstraints: 'NOT NULL',
    );
i0.MigrationStepWithVersion migrationSteps({
  required Future<void> Function(i1.Migrator m, Schema2 schema) from1To2,
  required Future<void> Function(i1.Migrator m, Schema3 schema) from2To3,
  required Future<void> Function(i1.Migrator m, Schema4 schema) from3To4,
}) {
  return (currentVersion, database) async {
    switch (currentVersion) {
      case 1:
        final schema = Schema2(database: database);
        final migrator = i1.Migrator(database, schema);
        await from1To2(migrator, schema);
        return 2;
      case 2:
        final schema = Schema3(database: database);
        final migrator = i1.Migrator(database, schema);
        await from2To3(migrator, schema);
        return 3;
      case 3:
        final schema = Schema4(database: database);
        final migrator = i1.Migrator(database, schema);
        await from3To4(migrator, schema);
        return 4;
      default:
        throw ArgumentError.value('Unknown migration from $currentVersion');
    }
  };
}

i1.OnUpgrade stepByStep({
  required Future<void> Function(i1.Migrator m, Schema2 schema) from1To2,
  required Future<void> Function(i1.Migrator m, Schema3 schema) from2To3,
  required Future<void> Function(i1.Migrator m, Schema4 schema) from3To4,
}) => i0.VersionedSchema.stepByStepHelper(
  step: migrationSteps(
    from1To2: from1To2,
    from2To3: from2To3,
    from3To4: from3To4,
  ),
);
